services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    # Removed container_name and ports so we can scale this service
    restart: always
    env_file:
      - .env
    environment:
      # Override host variables for Docker environment
      - DB_HOST=pgbouncer
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - pgbouncer
      - redis
    networks:
      - app-network

  pgbouncer:
    image: edoburu/pgbouncer:latest
    restart: always
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_NAME: ticket_booking
      POOL_MODE: transaction
      MAX_CLIENT_CONN: 10000
      DEFAULT_POOL_SIZE: 100
      AUTH_TYPE: plain
    depends_on:
      - postgres
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: event-ticket-lb
    restart: always
    ports:
      - '3000:80' # Bind host 3000 to nginx 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    container_name: event-ticket-postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticket_booking
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: event-ticket-redis
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge
